version: "3.7"
services:  
  
  db:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "7001:1433"
    volumes:
      - /home/alireza/shared/mssql:/var/opt/mssql
    environment:
      SA_PASSWORD: "Az123456"
      ACCEPT_EULA: "Y"
  
  api:
    depends_on:
      - db  
    image: kookweb/api
    ports:
      - "8101:80"
    volumes:
      - /home/alireza/shared/web-server/kookweb/api/wwwroot:/app/wwwroot
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"